#!/bin/bash
if ["$(uname)" == "Darwin"]; then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew install fish python python3 neofetch curl git rvm
else
	sudo apt-get install software-properties-common && sudo apt-add-repository ppa:fish-shell/release-2 && sudo apt-add-repository -y ppa:rael-gc/rvm && sudo apt-add-repository ppa:neovim-ppa/stable && sudo apt-get update && sudo apt-get install ssh python-dev python-pip python3-dev python3-pip curl clang libclang-dev git neofetch gcc rvm && rvm install ruby && sudo pip3 install neovim && sudo apt-get install python3-neovim && sudo chsh -s /usr/bin/fish && cd ~/.config && mkdir nvim && cd nvim && ln -s ~/VimSetup/init.vim init.vim && cd ~/.local/share && mkdir nvim && cd nvim && mkdir site && cd site && mkdir autoload && curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && cd ~/.config/fish && rm config.fish && ln -s ~/VimSetup/config.fish && cd ~/ && ln -s ~/VimSetup/init.vim .vimrc && ln -s ~/.local/share/nvim .vim && vi ~/.vimrc
fi	
