#!/bin/bash
if [[ "$(uname)" == "Darwin" ]]; then
	brew install python3 python2 curl neofetch gcc fish && curl -L https://get.oh-my.fish | fish && omw install bobthefish
else
	sudo apt-get install ssh python-dev python-pip python3-dev python3-pip curl clang libclang-dev git neofetch gcc rvm fish && mkdir ~/.config/fish &&  cd ~/.config/fish && ln -s ~/VimSetup/linuxconfig.fish config.fish && curl -L --create-dirs -o ~/.config/fish/functions/rvm.fish https://raw.github.com/lunks/fish-nuggets/master/functions/rvm.fish && echo "rvm default" >> ~/.config/fish/config.fish  && curl -L https://get.oh-my.fish | fish && omw install bobthefish
fi

