#!/bin/bash
if ["$(uname)" == "Darwin"]; then
	brew install python3 python2 curl neofetch gcc fish && curl -L https://get.oh-my.fish | fish && omw install bobthefish
else
	sudo apt-get install ssh python-dev python-pip python3-dev python3-pip curl clang libclang-dev git neofetch gcc rvm fish && curl -L https://get.oh-my.fish | fish && omw install bobthefish
fi
