#!/bin/bash
if [[ "$(uname)" == "Darwin" ]]; then
	sudo -H pip3 install neovim && sudo -H pip3 install flake8 && brew isntall neovim && sudo chsh -s /usr/local/bin/fish && cd ~/.config/nvim && rm init.vim ln -s ~/VimSetup/init.vim init.vim && cd ~/.local/share/nvim/ && curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && cp -rf ~/.local/share/nvim/site/autoload ../ && cd ~/.config/fish && rm config.fish && ln -s ~/VimSetup/macconfig.fish config.fish && cd ~/ && ln -s ~/VimSetup/init.vim .vimrc && cd ~/VimSetup/ && vi init.vim 
else
	pip3 install --user neovim && pip3 install --user flake8 && sudo apt-get install python3-neovim && sudo apt-get install neovim && sudo chsh -s /usr/bin/fish && cd ~/.config && mkdir nvim && cd nvim && ln -s ~/VimSetup/init.vim init.vim && cd ~/.local/share/ && mkdir nvim && cd nvim && mkdir site && curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && cp -rf ~/.local/share/nvim/site/autoload ../ && cd ~/ && ln -s ~/VimSetup/init.vim .vimrc && ln -s ~/.local/share/nvim .vim && gem install neovim &&  vi ~/.vimrc
fi
