#!/bin/bash
if [[ "$(uname)" == "Darwin" ]]; then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" && brew install fish python python3 neofetch curl git rvm
else
	sudo apt-get install software-properties-common curl gpg && gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 &&\curl -sSL https://get.rvm.io | bash -s stable --ruby && source ~/.rvm/scripts/rvm
fi	
echo "Logout and Login for group changes to update"
