#!/bin/bash
sudo apt-get install ssh python-dev python-pip python3-dev python3-pip curl clang libclang-dev git neofetch gcc rvm && sudo groupadd rvm && sudo useradd -G {rvm} leeas && source /etc/profile.d/rvm.sh
